apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-nginx
# spec:
  # selector:
  #   matchLabels:
  #     app: myapp
  # serviceName: <ServiceName>
  # replicas: 2
  # template:
  #   metadata:
  #     labels:
  #       app: myapp
  #   spec:
  #     containers:
  #     - name: myapp
  #       image: registry.k8s.io/nginx-slim:0.8
  #       ports:
  #       - containerPort: 80
  #         name: web
  #       volumeMounts:
  #       - name: www
  #         mountPath: /usr/share/nginx/html
  # volumeClaimTemplates:
  # - metadata:
  #     name: www
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 1Gi
spec:
  replicas: 3
  serviceName: sts-nginx 
  selector:
    matchLabels:
      app: po-nginx
  template:
    metadata:
      labels:
        app: po-nginx
    spec:
      containers:
        - name: po-nginx
          image: nginx
