apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-w-tolerations
  labels:
    app: deployment-w-tolerations
  spec:
    selector:
      matchLabels:
        app: deployment-w-tolerations
    template:
      metadata:
        labels:
          app: deployment-w-tolerations
      spec:
        containers:
        - name: nginx
          image: nginx
        tolerations:
        - effect: NoSchedule
          key: DB
          value: customer-info
