apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nfs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-nfs
  template:
    metadata:
      labels:
        app: deploy-nfs
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: nfs-vol
          mountPath: /audit
      volumes:
      - name: nfs-vol
        nfs:
          server: 192.168.65.3
          path: /nfs_shared/nfs-vol
