apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deploy-hostpath
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-hostpath
  template:
    metadata:
      labels:
        app: deploy-hostpath
    spec:
      containers:
      - name: host-mon
        image: nginx
        volumeMounts:
        - mountPath: /host-log
          name: hostpath-dir
      volumes:
      - name: hostpath-dir
        hostPath: 
          path: /var/log
