apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  labels:
    app: deploy-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-nginx
  template:
    metadata:
      labels:
        app: deploy-nginx
    spec:
      containers:
      - name: nginx
        image: nginx

---

apiVersion: v1
kind: Service
metadata:
  name: external-data
spec:
  type: ClusterIP
  selector:
    app: deploy-nginx
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: v1
kind: Endpoints
metadata:
  name: external-data
subsets:
- addresses: 
  - ip: 192.168.65.3 
  ports:
  - name: http
    port: 80