apiVersion: v1
kind: Pod
metadata:
  name: pod-adapter
  labels:
    name: nginx
spec:
  containers:
  - name: web-page
    image: nginx
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d

  - name: adapter
    image: nginx/nginx-prometheus-exporter
    env:
    - name: SCRAE_URI
      value: http://localhost/stub_status
    ports:
    - containerPort: 9113

  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-conf
      items:
      - key: default.conf
        path: default.conf
