apiVersion: v1
kind: Pod
metadata:
  name: on-failure
  labels:
    name: on-failure
spec:
  containers:
  - name: net-tools
    image: alpine
    command:
    - /bin/sh
    - "-c"
    args:
    - ls -al
  restartPolicy: OnFailure